remote_theme: pmarsceill/just-the-docs

title: RockKV - A Distributed Key-Value Store
description: A Distributed Key-Value Store
baseurl: "/rock-kv"
url: "https://navin-mohan.github.io"

aux_links:
  "RockKV on GitHub":
    - "//github.com/navin-mohan/rock-kv"
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

ga_tracking: G-0Y237M3RXT
